### ISSUE TITLE
Amazon Cloud Drive Client ID and Secret

### ISSUE THREAD

**Issue by c64bob** [ddurdle/PERL-CloudSync#4]
Hi ddurdle,

now I'm trying to authorize your script for my Amazon Cloud Drive. Do I need to register my own API to receive a client id and secret, or is there something I can use already?

Thanks

**Comment by ddurdle** [comment]
You need to add these two lines to config.cfg (after CLIENT_SECRET line)

use constant ACDCLIENT_ID => '####';
use constant ACDCLIENT_SECRET => '####';

You may use mine, if you can email me at ddurdle AT gmail DOT com

**Comment by c64bob** [comment]
Perfect. I quickly followed the process at Amazon Developper Portal and got my own ID and Secret.
